apiVersion: v1
kind: ConfigMap
metadata:
  name: video-service-config
  labels:
    app.kubernetes.io/name: video-service
    app.kubernetes.io/part-of: fiapx
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.fiapx.svc.cluster.local:5432/videodb"
  SPRING_DATA_REDIS_HOST: "redis.fiapx.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_RABBITMQ_HOST: "rabbitmq.fiapx.svc.cluster.local"
  SPRING_RABBITMQ_PORT: "5672"
  MINIO_ENDPOINT: "http://minio.fiapx.svc.cluster.local:9000"
  MINIO_BUCKET_VIDEOS: "fiapx-videos"
  MINIO_BUCKET_OUTPUTS: "fiapx-outputs"
  SPRING_MAIL_HOST: "mailhog.fiapx.svc.cluster.local"
  SPRING_MAIL_PORT: "1025"
