apiVersion: v1
kind: Service
metadata:
  name: video-service
  labels:
    app.kubernetes.io/name: video-service
    app.kubernetes.io/part-of: fiapx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: video-service
  ports:
    - name: http
      port: 8081
      targetPort: http
