apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: fiapx
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.fiapx.svc.cluster.local:9090
        isDefault: true
        editable: false
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: fiapx
        orgId: 1
        folder: FIAP X
        type: file
        disableDeletion: false
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false
