apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: fiapx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fiapx-prometheus
  labels:
    app.kubernetes.io/part-of: fiapx
rules:
  # service discovery: descobre os pods a serem raspados
  - apiGroups: [""]
    resources: [nodes, nodes/metrics, services, endpoints, pods]
    verbs: [get, list, watch]
  - nonResourceURLs: ["/metrics"]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fiapx-prometheus
  labels:
    app.kubernetes.io/part-of: fiapx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fiapx-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: fiapx
